---
- name: Load OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution|lower }}.yml"
        - "{{ ansible_os_family|lower }}.yml"
        - defaults.yml
      paths:
        - ../vars

- name: Download the Ambari repo
  get_url: url={{ ambari_repo }} dest={{ ambari_repo_file }}

- name: Get HDP repo urlinfo
  uri: url="http://public-repo-1.hortonworks.com/HDP/hdp_urlinfo.json" return_content=yes
  register: json_response

- name: Add apt key
  apt_key: keyserver=keyserver.ubuntu.com id={{ ambari_repo_key }}
  when: ansible_os_family == "Debian"

- name: Cache Ambari and dependant packages
  raw: time yum -y install --downloadonly $(yum list available | awk '$3 ~ /ambari/ {print $1}') java-1.8.0-openjdk-devel
  when: cache_packages is defined and cache_packages and ansible_os_family == "RedHat"

- name: Install OpenJDK
  raw: yum -y install java-1.8.0-openjdk-devel
  when: cache_packages is defined and cache_packages and ansible_os_family == "RedHat"

- name: Download the HDP repo
  get_url: url={{ (json_response.content|from_json)['HDP-{{ hdp_version }}']['latest']['centos-{{ ansible_distribution|lower }}'] }}hdp.repo dest=/etc/yum.repos.d/HDP.repo
  when: cache_packages is defined and cache_packages and ansible_os_family == "RedHat"

- name: Pre-install HDP packages
  raw: yum -y install $(yum list available | awk '$3~/HDP-[1-9]/ && $1~/^(falcon|hadoop|hadooplzo|hive|oozie|pig|spark|sqoop|tez|zookeeper)_[0-9]_[0-9]/ {print $1}')
  when: cache_packages is defined and cache_packages and ansible_os_family == "RedHat"

#- name: Remove HDP repo
  #file: path=/etc/yum.repos.d/HDP.repo state=absent
  #when: cache_packages is defined and cache_packages and ansible_os_family == "RedHat"

#- name: Move foo to bar
  #command: mv /etc/yum.repos.d/HDP.repo /etc/yum.repos.d/HDP.repo.orig
  #when: cache_packages is defined and cache_packages and ansible_os_family == "RedHat"
