---
- name: Load OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution|lower }}.yml"
        - "{{ ansible_os_family|lower }}.yml"
        - defaults.yml
      paths:
        - ../vars

- name: Download the Ambari repo
  get_url: url={{ ambari_repo }} dest={{ ambari_repo_file }}

- name: Get HDP repo urlinfo
  uri: url="http://public-repo-1.hortonworks.com/HDP/hdp_urlinfo.json" return_content=yes
  register: json_response

- debug: msg="Success - tag defined =>{{  (json_response.content|from_json)['HDP-2.4']['latest']['centos7'] }}<="
  when:  (json_response.content|from_json)['HDP-2.4']['latest']['centos7']  is defined

- name: Download the HDP repo
  get_url: url={{ (json_response.content|from_json)['HDP-2.4']['latest']['centos7'] }}hdp.repo dest=/etc/yum.repos.d/HDPcache.repo

- name: Add apt key
  apt_key: keyserver=keyserver.ubuntu.com id={{ ambari_repo_key }}
  when: ansible_os_family == "Debian"

- name: Cache Ambari and dependant packages
  raw: time yum -y install --downloadonly $(yum list all | awk '$3 ~ /ambari/ {print $1}') java-1.8.0-openjdk-devel
  when: cache_packages is defined and cache_packages and ansible_os_family == "RedHat"

- name: Cache Ambari and dependant packages
  raw: time yum -y install $(yum list all | awk '$3 ~ /HDP-2.4/ {print $1}' | grep "^hadoop")
  when: cache_packages is defined and cache_packages and ansible_os_family == "RedHat"

- name: Remove HDP repo
  file: path=/etc/yum.repos.d/HDPcache.repo state=absent
