---
- name: Load OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution|lower }}.yml"
        - "{{ ansible_os_family|lower }}.yml"
        - defaults.yml
      paths:
        - ../vars

- name: Download the Ambari repo
  get_url: url={{ ambari_repo }} dest={{ ambari_repo_file }}

- name: Add apt key
  apt_key: keyserver=keyserver.ubuntu.com id={{ ambari_repo_key }}
  when: ansible_os_family == "Debian"

## Used for building base images
- name: Cache Ambari and dependant packages
  raw: time yum -y install --downloadonly $(yum list all | awk '$3 ~ /ambari/ {print $1}') java-1.8.0-openjdk-devel
  when: cache_packages is defined and cache_packages and ansible_os_family == "RedHat"

