packages:
  - python-simplejson
  - python-httplib2
  - man
  - man-pages
  - vim-enhanced
  - sysstat
  - lsof
  - jwhois
  - telnet
  - nc
  - libselinux-python
  - ntp
  - parted
  - mc
  - perl
  - openssh-clients
  - util-linux-ng
  - iotop
  - links
  - unzip
  - curl
  - wget

update_info:
  pkg_mgr: yum
  args:
    pkg: "*"
    state: latest
    update_cache: yes

ntp_service: ntpd
ntp_sync: "/usr/sbin/ntpd -gq"

epel_url: "http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm"

resolv_conf: "/etc/resolv.conf"

networking_path: "/etc/sysconfig/network-scripts"
networking_eth: "redhat-ifcfg-eth.j2"
networking_bond: "redhat-ifcfg-bond.j2"

java_version: 8
