ansible_distribution_major_version: 6

ambari_repo: "http://{{ ambari_repo_host }}/ambari/centos6/2.x/updates/{{ ambari_version }}/ambari.repo"
ambari_repo_gpgkey: "http://{{ ambari_repo_host }}/ambari/centos6/RPM-GPG-KEY/RPM-GPG-KEY-Jenkins"
ambari_repo_file: "/etc/yum.repos.d/ambari.repo"

