---
- name: "Add Ambari Master to required groups"
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: "Add the last masternode to ambari-node variable group if not present"
      always_run: yes
      add_host:
        name: "{{ hostvars[item].inventory_hostname }}"
        ansible_host: "{{ item }}"
        ansible_user: "{{ hostvars[item].ansible_user|default('root') }}"
        ansible_ssh_pass: "{{ hostvars[item].ansible_ssh_pass|default('') }}"
        ansible_become_user: root
        ansible_become_pass: "{{ hostvars[item].ansible_ssh_pass|default('') }}"
        groups: ambari-node
      with_items: "{{ groups['master-nodes']|last }}"
      when: groups['tag_role_ambari_node']|length < 1

- name: "Show debug info"
  hosts: hadoop-cluster
  become: yes
  tasks:
    - name: "Show hadoop-cluster info"
      debug: var=hostvars[inventory_hostname]
      when: debug

- name: "Apply the ambari-agent role to all nodes"
  hosts: hadoop-cluster
  any_errors_fatal: true
  become: yes
  roles:
    - ambari-agent
  tags:
    - ambari-agent-only

- name: "Apply the ambari-server role to ambari-node group"
  hosts: ambari-node
  become: yes
  roles:
    - ambari-server
  tags:
    - ambari-server-only
