---
- name: "Build the environment"
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Create the SSH keypair
      local_action:
        module: rax_keypair
        credentials: "{{ cloud_config.rax_credentials_file }}"
        name: "{{ cloud_config.ssh.keyname }}"
        public_key: "{{ lookup('file', cloud_config.ssh.keyfile) }}"
        region: "{{ cloud_config.rax_region }}"

    - name: Include master-nodes group variables
      include_vars: group_vars/master-nodes

    - name: "Create master nodes"
      local_action:
        module: rax
        credentials: "{{ cloud_config.rax_credentials_file }}"
        name: "master-%02d.{{ cloud_config.domain }}"
        image: "{{ cloud_image }}"
        flavor: "{{ cloud_flavor }}"
        count: "{{ cloud_nodes_count }}"
        region: "{{ cloud_config.rax_region }}"
        key_name: "{{ cloud_config.ssh.keyname }}"
        exact_count: yes
        auto_increment: true
        group: master-nodes
        state: present
        wait: true
        wait_timeout: 900
      register: rax
      when: cloud_nodes_count > 0

    - name: "Build Rackspace CBS for master nodes"
      include: provision_cbs.yml
      when: cloud_nodes_count > 0 and build_datanode_cbs is defined and build_datanode_cbs

    - name: Include slave-nodes group variables
      include_vars: group_vars/slave-nodes

    - name: "Create slave nodes"
      local_action:
        module: rax
        credentials: "{{ cloud_config.rax_credentials_file }}"
        name: "slave-%02d.{{ cloud_config.domain }}"
        image: "{{ cloud_image }}"
        flavor: "{{ cloud_flavor }}"
        count: "{{ cloud_nodes_count }}"
        region: "{{ cloud_config.rax_region }}"
        key_name: "{{ cloud_config.ssh.keyname }}"
        exact_count: yes
        auto_increment: true
        group: slave-nodes
        state: present
        wait: true
        wait_timeout: 900
      register: rax
      when: cloud_nodes_count > 0

    - name: "Build Rackspace CBS for slave nodes"
      include: provision_cbs.yml
      when: cloud_nodes_count > 0 and build_datanode_cbs is defined and build_datanode_cbs

    - name: Include edge-nodes group variables
      include_vars: group_vars/edge-nodes

    - name: "Create edge nodes"
      local_action:
        module: rax
        credentials: "{{ cloud_config.rax_credentials_file }}"
        name: "edge-%02d.{{ cloud_config.domain }}"
        image: "{{ cloud_image }}"
        flavor: "{{ cloud_flavor }}"
        count: "{{ cloud_nodes_count }}"
        region: "{{ cloud_config.rax_region }}"
        key_name: "{{ cloud_config.ssh.keyname }}"
        exact_count: yes
        auto_increment: true
        group: edge-nodes
        state: present
        wait: true
        wait_timeout: 900
      register: rax
      when: cloud_nodes_count > 0
