---
- name: Ensure required packages are installed (yum)
  yum:
    name: "{{ item }}"
    update_cache: yes
    state: installed
  with_items:
    - ambari-server
  notify: reload systemd
  when: ansible_os_family == "RedHat"

- name: Ensure required packages are installed (apt)
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: installed
  with_items:
    - ambari-server
  when: ansible_os_family == "Debian"

- meta: flush_handlers

- include: spark_stack.yml
  when: spark_stack and ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: Run Ambari Server setup
  shell: /usr/sbin/ambari-server setup -s
  when: java_type == "oracle" or java_type is undefined

- name: Run Ambari Server setup with OpenJDK
  shell: /usr/sbin/ambari-server setup -s -j /etc/alternatives/java_sdk
  when: java_type == "open"

- name: Make sure ambari-server is running
  service: name=ambari-server state=started enabled=yes

- name: Waiting for ambari-server to start listening on port 8080
  wait_for: host={{ ansible_fqdn }} port=8080

- name: Waiting for ambari-agents to register
  uri: url=http://{{ ansible_fqdn }}:8080/api/v1/hosts/{{ hostvars[item]['ansible_fqdn'] | lower }}
       method=GET
       force_basic_auth=yes
       user=admin
       password=admin
       HEADER_X-Requested-By="ambari"
       status_code=200,201,202,404
  with_items: "{{ groups['hadoop-cluster'] }}"
  register: result
  until: "result.status != 404"
  retries: 200
  delay: 5
